// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import type { ChangePasswordData, ChangePasswordErrors, CompleteUploadData, CompleteUploadErrors, CompleteUploadResponses, CreateUploadData, CreateUploadErrors, CreateUploadResponses, DeleteMeData, DeleteMeErrors, GetLivenessData, GetLivenessResponses, GetMeData, GetMeErrors, GetMeResponses, GetMySecurityLogData, GetMySecurityLogErrors, GetMySecurityLogResponses, GetReadinessData, GetReadinessErrors, GetReadinessResponses, ListAuditLogsData, ListAuditLogsErrors, ListAuditLogsResponses, ListSessionsData, ListSessionsErrors, ListSessionsResponses, LoginData, LoginErrors, LoginResponses, LogoutData, LogoutErrors, RefreshData, RefreshErrors, RefreshResponses, RegisterData, RegisterErrors, RegisterResponses, RemoveMyAvatarData, RemoveMyAvatarErrors, RequestPasswordResetData, RequestPasswordResetErrors, ResetPasswordData, ResetPasswordErrors, RevokeAllSessionsData, RevokeAllSessionsErrors, RevokeSessionData, RevokeSessionErrors, UpdateMyAvatarData, UpdateMyAvatarErrors } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

export const listAuditLogs = <ThrowOnError extends boolean = true>(options: Options<ListAuditLogsData, ThrowOnError>): RequestResult<ListAuditLogsResponses, ListAuditLogsErrors, ThrowOnError> => options.client.get<ListAuditLogsResponses, ListAuditLogsErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/admin/audit-logs',
    ...options
});

export const register = <ThrowOnError extends boolean = true>(options: Options<RegisterData, ThrowOnError>): RequestResult<RegisterResponses, RegisterErrors, ThrowOnError> => options.client.post<RegisterResponses, RegisterErrors, ThrowOnError>({
    url: '/api/v1/auth/register',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const login = <ThrowOnError extends boolean = true>(options: Options<LoginData, ThrowOnError>): RequestResult<LoginResponses, LoginErrors, ThrowOnError> => options.client.post<LoginResponses, LoginErrors, ThrowOnError>({
    url: '/api/v1/auth/login',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const refresh = <ThrowOnError extends boolean = true>(options: Options<RefreshData, ThrowOnError>): RequestResult<RefreshResponses, RefreshErrors, ThrowOnError> => options.client.post<RefreshResponses, RefreshErrors, ThrowOnError>({
    url: '/api/v1/auth/refresh',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const logout = <ThrowOnError extends boolean = true>(options: Options<LogoutData, ThrowOnError>): RequestResult<unknown, LogoutErrors, ThrowOnError> => options.client.post<unknown, LogoutErrors, ThrowOnError>({
    url: '/api/v1/auth/logout',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const changePassword = <ThrowOnError extends boolean = true>(options: Options<ChangePasswordData, ThrowOnError>): RequestResult<unknown, ChangePasswordErrors, ThrowOnError> => options.client.post<unknown, ChangePasswordErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/auth/password/change',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const requestPasswordReset = <ThrowOnError extends boolean = true>(options: Options<RequestPasswordResetData, ThrowOnError>): RequestResult<unknown, RequestPasswordResetErrors, ThrowOnError> => options.client.post<unknown, RequestPasswordResetErrors, ThrowOnError>({
    url: '/api/v1/auth/password/forgot',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const resetPassword = <ThrowOnError extends boolean = true>(options: Options<ResetPasswordData, ThrowOnError>): RequestResult<unknown, ResetPasswordErrors, ThrowOnError> => options.client.post<unknown, ResetPasswordErrors, ThrowOnError>({
    url: '/api/v1/auth/password/reset',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const revokeAllSessions = <ThrowOnError extends boolean = true>(options: Options<RevokeAllSessionsData, ThrowOnError>): RequestResult<unknown, RevokeAllSessionsErrors, ThrowOnError> => options.client.delete<unknown, RevokeAllSessionsErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/auth/sessions',
    ...options
});

export const listSessions = <ThrowOnError extends boolean = true>(options: Options<ListSessionsData, ThrowOnError>): RequestResult<ListSessionsResponses, ListSessionsErrors, ThrowOnError> => options.client.get<ListSessionsResponses, ListSessionsErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/auth/sessions',
    ...options
});

export const revokeSession = <ThrowOnError extends boolean = true>(options: Options<RevokeSessionData, ThrowOnError>): RequestResult<unknown, RevokeSessionErrors, ThrowOnError> => options.client.delete<unknown, RevokeSessionErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/auth/sessions/{id}',
    ...options
});

export const createUpload = <ThrowOnError extends boolean = true>(options: Options<CreateUploadData, ThrowOnError>): RequestResult<CreateUploadResponses, CreateUploadErrors, ThrowOnError> => options.client.post<CreateUploadResponses, CreateUploadErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/files/uploads',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const completeUpload = <ThrowOnError extends boolean = true>(options: Options<CompleteUploadData, ThrowOnError>): RequestResult<CompleteUploadResponses, CompleteUploadErrors, ThrowOnError> => options.client.post<CompleteUploadResponses, CompleteUploadErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/files/{id}/complete',
    ...options
});

export const deleteMe = <ThrowOnError extends boolean = true>(options: Options<DeleteMeData, ThrowOnError>): RequestResult<unknown, DeleteMeErrors, ThrowOnError> => options.client.delete<unknown, DeleteMeErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/users/me',
    ...options
});

export const getMe = <ThrowOnError extends boolean = true>(options: Options<GetMeData, ThrowOnError>): RequestResult<GetMeResponses, GetMeErrors, ThrowOnError> => options.client.get<GetMeResponses, GetMeErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/users/me',
    ...options
});

export const getMySecurityLog = <ThrowOnError extends boolean = true>(options: Options<GetMySecurityLogData, ThrowOnError>): RequestResult<GetMySecurityLogResponses, GetMySecurityLogErrors, ThrowOnError> => options.client.get<GetMySecurityLogResponses, GetMySecurityLogErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/users/me/security-log',
    ...options
});

export const removeMyAvatar = <ThrowOnError extends boolean = true>(options: Options<RemoveMyAvatarData, ThrowOnError>): RequestResult<unknown, RemoveMyAvatarErrors, ThrowOnError> => options.client.delete<unknown, RemoveMyAvatarErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/users/me/avatar',
    ...options
});

export const updateMyAvatar = <ThrowOnError extends boolean = true>(options: Options<UpdateMyAvatarData, ThrowOnError>): RequestResult<unknown, UpdateMyAvatarErrors, ThrowOnError> => options.client.put<unknown, UpdateMyAvatarErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/users/me/avatar',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const getLiveness = <ThrowOnError extends boolean = true>(options: Options<GetLivenessData, ThrowOnError>): RequestResult<GetLivenessResponses, unknown, ThrowOnError> => options.client.get<GetLivenessResponses, unknown, ThrowOnError>({ url: '/api/health/live', ...options });

export const getReadiness = <ThrowOnError extends boolean = true>(options: Options<GetReadinessData, ThrowOnError>): RequestResult<GetReadinessResponses, GetReadinessErrors, ThrowOnError> => options.client.get<GetReadinessResponses, GetReadinessErrors, ThrowOnError>({ url: '/api/health/ready', ...options });
