// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: string;
};

export type AuditLogPage = {
    data: Array<AuditLog>;
    meta: {
        page: number;
        limit: number;
        total: number;
        hasMore: boolean;
    };
};

export type AuditLog = {
    id: string;
    event: string;
    outcome: 'SUCCESS' | 'FAILURE';
    actorId: string | null;
    subjectId: string | null;
    targetType: string | null;
    targetId: string | null;
    metadata: unknown;
    ip: string | null;
    userAgent: string | null;
    requestId: string | null;
    createdAt: string;
};

export type ErrorResponse = {
    statusCode: number;
    code: string;
    message: string;
    timestamp: string;
    path: string;
    requestId?: string;
    errors?: Array<ValidationIssue>;
};

export type ValidationIssue = {
    field: string | null;
    code: string;
    message: string;
};

export type RegisterRequest = {
    email: string;
    password: string;
};

export type TokenPair = {
    accessToken: string;
    refreshToken: string;
};

export type LoginRequest = {
    email: string;
    password: string;
};

export type LoginResponse = {
    accessToken: string;
    refreshToken: string;
    reactivated: boolean;
};

export type RefreshRequest = {
    refreshToken: string;
};

export type ChangePasswordRequest = {
    currentPassword: string;
    newPassword: string;
};

export type ForgotPasswordRequest = {
    email: string;
};

export type ResetPasswordRequest = {
    token: string;
    newPassword: string;
};

export type Session = {
    id: string;
    device: string | null;
    ip: string | null;
    userAgent: string | null;
    isCurrent: boolean;
    lastUsedAt: string;
    createdAt: string;
};

export type CreateUploadRequest = {
    purpose: string;
    contentType: string;
    size: number;
    fileName?: string;
};

export type UploadTicket = {
    fileId: string;
    uploadUrl: string;
    method: 'PUT';
    headers: {
        [key: string]: string;
    };
    expiresAt: string;
};

export type StoredFile = {
    id: string;
    contentType: string;
    size: number;
    width: number | null;
    height: number | null;
    url: string | null;
    variants: {
        [key: string]: string;
    };
};

export type Me = {
    id: string;
    email: string;
    role: 'USER' | 'ADMIN';
    createdAt: string;
    lastLoginAt: string | null;
    avatar: StoredFile | null;
};

export type SecurityLogPage = {
    data: Array<SecurityLogEntry>;
    meta: {
        nextCursor: string | null;
        hasMore: boolean;
    };
};

export type SecurityLogEntry = {
    id: string;
    event: string;
    outcome: 'SUCCESS' | 'FAILURE';
    targetType: string | null;
    targetId: string | null;
    ip: string | null;
    userAgent: string | null;
    createdAt: string;
};

export type UpdateAvatarRequest = {
    fileId: string;
};

export type Liveness = {
    status: 'ok';
    uptime: number;
};

export type Readiness = {
    status: 'ready' | 'not_ready';
    checks: {
        database: 'up' | 'down';
    };
};

export type ListAuditLogsData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        limit?: number;
        event?: string;
        outcome?: 'SUCCESS' | 'FAILURE';
        actorId?: string;
        subjectId?: string;
        targetType?: string;
        targetId?: string;
        from?: string;
        to?: string;
    };
    url: '/api/v1/admin/audit-logs';
};

export type ListAuditLogsErrors = {
    401: ErrorResponse;
    403: ErrorResponse;
    422: ErrorResponse;
    429: ErrorResponse;
};

export type ListAuditLogsError = ListAuditLogsErrors[keyof ListAuditLogsErrors];

export type ListAuditLogsResponses = {
    200: AuditLogPage;
};

export type ListAuditLogsResponse = ListAuditLogsResponses[keyof ListAuditLogsResponses];

export type RegisterData = {
    body: RegisterRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/register';
};

export type RegisterErrors = {
    409: ErrorResponse;
    422: ErrorResponse;
    429: ErrorResponse;
};

export type RegisterError = RegisterErrors[keyof RegisterErrors];

export type RegisterResponses = {
    201: TokenPair;
};

export type RegisterResponse = RegisterResponses[keyof RegisterResponses];

export type LoginData = {
    body: LoginRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/login';
};

export type LoginErrors = {
    401: ErrorResponse;
    422: ErrorResponse;
    429: ErrorResponse;
};

export type LoginError = LoginErrors[keyof LoginErrors];

export type LoginResponses = {
    200: LoginResponse;
};

export type LoginResponse2 = LoginResponses[keyof LoginResponses];

export type RefreshData = {
    body: RefreshRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/refresh';
};

export type RefreshErrors = {
    401: ErrorResponse;
    422: ErrorResponse;
    429: ErrorResponse;
};

export type RefreshError = RefreshErrors[keyof RefreshErrors];

export type RefreshResponses = {
    200: TokenPair;
};

export type RefreshResponse = RefreshResponses[keyof RefreshResponses];

export type LogoutData = {
    body: RefreshRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/logout';
};

export type LogoutErrors = {
    422: ErrorResponse;
    429: ErrorResponse;
};

export type LogoutError = LogoutErrors[keyof LogoutErrors];

export type ChangePasswordData = {
    body: ChangePasswordRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/password/change';
};

export type ChangePasswordErrors = {
    401: ErrorResponse;
    422: ErrorResponse;
    429: ErrorResponse;
};

export type ChangePasswordError = ChangePasswordErrors[keyof ChangePasswordErrors];

export type RequestPasswordResetData = {
    body: ForgotPasswordRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/password/forgot';
};

export type RequestPasswordResetErrors = {
    422: ErrorResponse;
    429: ErrorResponse;
};

export type RequestPasswordResetError = RequestPasswordResetErrors[keyof RequestPasswordResetErrors];

export type ResetPasswordData = {
    body: ResetPasswordRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/password/reset';
};

export type ResetPasswordErrors = {
    422: ErrorResponse;
    429: ErrorResponse;
};

export type ResetPasswordError = ResetPasswordErrors[keyof ResetPasswordErrors];

export type RevokeAllSessionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/sessions';
};

export type RevokeAllSessionsErrors = {
    401: ErrorResponse;
    429: ErrorResponse;
};

export type RevokeAllSessionsError = RevokeAllSessionsErrors[keyof RevokeAllSessionsErrors];

export type ListSessionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/sessions';
};

export type ListSessionsErrors = {
    401: ErrorResponse;
    429: ErrorResponse;
};

export type ListSessionsError = ListSessionsErrors[keyof ListSessionsErrors];

export type ListSessionsResponses = {
    200: Array<Session>;
};

export type ListSessionsResponse = ListSessionsResponses[keyof ListSessionsResponses];

export type RevokeSessionData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/auth/sessions/{id}';
};

export type RevokeSessionErrors = {
    401: ErrorResponse;
    404: ErrorResponse;
    422: ErrorResponse;
    429: ErrorResponse;
};

export type RevokeSessionError = RevokeSessionErrors[keyof RevokeSessionErrors];

export type CreateUploadData = {
    body: CreateUploadRequest;
    path?: never;
    query?: never;
    url: '/api/v1/files/uploads';
};

export type CreateUploadErrors = {
    401: ErrorResponse;
    403: ErrorResponse;
    422: ErrorResponse;
    429: ErrorResponse;
};

export type CreateUploadError = CreateUploadErrors[keyof CreateUploadErrors];

export type CreateUploadResponses = {
    201: UploadTicket;
};

export type CreateUploadResponse = CreateUploadResponses[keyof CreateUploadResponses];

export type CompleteUploadData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/files/{id}/complete';
};

export type CompleteUploadErrors = {
    401: ErrorResponse;
    404: ErrorResponse;
    422: ErrorResponse;
    429: ErrorResponse;
    503: ErrorResponse;
};

export type CompleteUploadError = CompleteUploadErrors[keyof CompleteUploadErrors];

export type CompleteUploadResponses = {
    200: StoredFile;
};

export type CompleteUploadResponse = CompleteUploadResponses[keyof CompleteUploadResponses];

export type DeleteMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type DeleteMeErrors = {
    401: ErrorResponse;
    404: ErrorResponse;
    429: ErrorResponse;
};

export type DeleteMeError = DeleteMeErrors[keyof DeleteMeErrors];

export type GetMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type GetMeErrors = {
    401: ErrorResponse;
    404: ErrorResponse;
    429: ErrorResponse;
};

export type GetMeError = GetMeErrors[keyof GetMeErrors];

export type GetMeResponses = {
    200: Me;
};

export type GetMeResponse = GetMeResponses[keyof GetMeResponses];

export type GetMySecurityLogData = {
    body?: never;
    path?: never;
    query?: {
        cursor?: string;
        limit?: number;
    };
    url: '/api/v1/users/me/security-log';
};

export type GetMySecurityLogErrors = {
    401: ErrorResponse;
    422: ErrorResponse;
    429: ErrorResponse;
};

export type GetMySecurityLogError = GetMySecurityLogErrors[keyof GetMySecurityLogErrors];

export type GetMySecurityLogResponses = {
    200: SecurityLogPage;
};

export type GetMySecurityLogResponse = GetMySecurityLogResponses[keyof GetMySecurityLogResponses];

export type RemoveMyAvatarData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me/avatar';
};

export type RemoveMyAvatarErrors = {
    401: ErrorResponse;
    404: ErrorResponse;
    429: ErrorResponse;
};

export type RemoveMyAvatarError = RemoveMyAvatarErrors[keyof RemoveMyAvatarErrors];

export type UpdateMyAvatarData = {
    body: UpdateAvatarRequest;
    path?: never;
    query?: never;
    url: '/api/v1/users/me/avatar';
};

export type UpdateMyAvatarErrors = {
    401: ErrorResponse;
    404: ErrorResponse;
    422: ErrorResponse;
    429: ErrorResponse;
};

export type UpdateMyAvatarError = UpdateMyAvatarErrors[keyof UpdateMyAvatarErrors];

export type GetLivenessData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/health/live';
};

export type GetLivenessResponses = {
    200: Liveness;
};

export type GetLivenessResponse = GetLivenessResponses[keyof GetLivenessResponses];

export type GetReadinessData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/health/ready';
};

export type GetReadinessErrors = {
    503: Readiness;
};

export type GetReadinessError = GetReadinessErrors[keyof GetReadinessErrors];

export type GetReadinessResponses = {
    200: Readiness;
};

export type GetReadinessResponse = GetReadinessResponses[keyof GetReadinessResponses];
