// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

export const zAuditLog = z.object({
    id: z.string(),
    event: z.string(),
    outcome: z.enum(['SUCCESS', 'FAILURE']),
    actorId: z.string().nullable(),
    subjectId: z.string().nullable(),
    targetType: z.string().nullable(),
    targetId: z.string().nullable(),
    metadata: z.unknown(),
    ip: z.string().nullable(),
    userAgent: z.string().nullable(),
    requestId: z.string().nullable(),
    createdAt: z.iso.datetime()
});

export const zAuditLogPage = z.object({
    data: z.array(zAuditLog),
    meta: z.object({
        page: z.int().gte(-9007199254740991).lte(9007199254740991),
        limit: z.int().gte(-9007199254740991).lte(9007199254740991),
        total: z.int().gte(-9007199254740991).lte(9007199254740991),
        hasMore: z.boolean()
    })
});

export const zValidationIssue = z.object({
    field: z.string().nullable(),
    code: z.string(),
    message: z.string()
});

export const zErrorResponse = z.object({
    statusCode: z.int().gte(-9007199254740991).lte(9007199254740991),
    code: z.string(),
    message: z.string(),
    timestamp: z.string(),
    path: z.string(),
    requestId: z.string().optional(),
    errors: z.array(zValidationIssue).optional()
});

export const zRegisterRequest = z.object({
    email: z.email().regex(/^(?:[A-Za-z0-9_'+\-]+\.)*[A-Za-z0-9_'+\-]*[A-Za-z0-9_+-]@(?:[A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$/),
    password: z.string().min(8).max(128)
});

export const zTokenPair = z.object({
    accessToken: z.string(),
    accessTokenExpiresIn: z.int().gte(-9007199254740991).lte(9007199254740991),
    refreshToken: z.string(),
    refreshTokenExpiresIn: z.int().gte(-9007199254740991).lte(9007199254740991)
});

export const zLoginRequest = z.object({
    email: z.email().regex(/^(?:[A-Za-z0-9_'+\-]+\.)*[A-Za-z0-9_'+\-]*[A-Za-z0-9_+-]@(?:[A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$/),
    password: z.string().min(1)
});

export const zLoginResponse = z.object({
    accessToken: z.string(),
    accessTokenExpiresIn: z.int().gte(-9007199254740991).lte(9007199254740991),
    refreshToken: z.string(),
    refreshTokenExpiresIn: z.int().gte(-9007199254740991).lte(9007199254740991),
    reactivated: z.boolean()
});

export const zRefreshRequest = z.object({
    refreshToken: z.string().min(1)
});

export const zChangePasswordRequest = z.object({
    currentPassword: z.string().min(1),
    newPassword: z.string().min(8).max(128)
});

export const zForgotPasswordRequest = z.object({
    email: z.email().regex(/^(?:[A-Za-z0-9_'+\-]+\.)*[A-Za-z0-9_'+\-]*[A-Za-z0-9_+-]@(?:[A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$/)
});

export const zResetPasswordRequest = z.object({
    token: z.string().min(1),
    newPassword: z.string().min(8).max(128)
});

export const zSession = z.object({
    id: z.string(),
    device: z.string().nullable(),
    ip: z.string().nullable(),
    userAgent: z.string().nullable(),
    isCurrent: z.boolean(),
    lastUsedAt: z.iso.datetime(),
    createdAt: z.iso.datetime()
});

export const zCreateUploadRequest = z.object({
    purpose: z.string().min(1).max(100),
    contentType: z.string().min(1).max(255),
    size: z.int().gt(0).lte(9007199254740991),
    fileName: z.string().min(1).max(255).optional()
});

export const zUploadTicket = z.object({
    fileId: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/),
    uploadUrl: z.string(),
    method: z.enum(['PUT']),
    headers: z.record(z.string(), z.string()),
    expiresAt: z.iso.datetime()
});

export const zStoredFile = z.object({
    id: z.string(),
    contentType: z.string(),
    size: z.int().gte(-9007199254740991).lte(9007199254740991),
    width: z.int().gte(-9007199254740991).lte(9007199254740991).nullable(),
    height: z.int().gte(-9007199254740991).lte(9007199254740991).nullable(),
    url: z.string().nullable(),
    variants: z.record(z.string(), z.string())
});

export const zMe = z.object({
    id: z.string(),
    email: z.string(),
    role: z.enum(['USER', 'ADMIN']),
    createdAt: z.iso.datetime(),
    lastLoginAt: z.iso.datetime().nullable(),
    avatar: zStoredFile.nullable()
});

export const zSecurityLogEntry = z.object({
    id: z.string(),
    event: z.string(),
    outcome: z.enum(['SUCCESS', 'FAILURE']),
    targetType: z.string().nullable(),
    targetId: z.string().nullable(),
    ip: z.string().nullable(),
    userAgent: z.string().nullable(),
    createdAt: z.iso.datetime()
});

export const zSecurityLogPage = z.object({
    data: z.array(zSecurityLogEntry),
    meta: z.object({
        nextCursor: z.string().nullable(),
        hasMore: z.boolean()
    })
});

export const zUpdateAvatarRequest = z.object({
    fileId: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/)
});

export const zLiveness = z.object({
    status: z.enum(['ok']),
    uptime: z.int().gte(-9007199254740991).lte(9007199254740991)
});

export const zReadiness = z.object({
    status: z.enum(['ready', 'not_ready']),
    checks: z.object({
        database: z.enum(['up', 'down'])
    })
});

export const zListAuditLogsQuery = z.object({
    page: z.int().gte(1).lte(9007199254740991).optional().default(1),
    limit: z.int().gte(1).lte(100).optional().default(20),
    event: z.string().min(1).optional(),
    outcome: z.enum(['SUCCESS', 'FAILURE']).optional(),
    actorId: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/).optional(),
    subjectId: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/).optional(),
    targetType: z.string().min(1).optional(),
    targetId: z.string().min(1).optional(),
    from: z.iso.datetime().regex(/^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d:[0-5]\d(?:\.\d+)?(?:Z))$/).optional(),
    to: z.iso.datetime().regex(/^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d:[0-5]\d(?:\.\d+)?(?:Z))$/).optional()
});

export const zListAuditLogsResponse = zAuditLogPage;

export const zRegisterBody = zRegisterRequest;

export const zRegisterResponse = zTokenPair;

export const zLoginBody = zLoginRequest;

export const zLoginResponse2 = zLoginResponse;

export const zRefreshBody = zRefreshRequest;

export const zRefreshResponse = zTokenPair;

export const zLogoutBody = zRefreshRequest;

export const zChangePasswordBody = zChangePasswordRequest;

export const zRequestPasswordResetBody = zForgotPasswordRequest;

export const zResetPasswordBody = zResetPasswordRequest;

export const zListSessionsResponse = z.array(zSession);

export const zRevokeSessionPath = z.object({
    id: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/)
});

export const zCreateUploadBody = zCreateUploadRequest;

export const zCreateUploadResponse = zUploadTicket;

export const zCompleteUploadPath = z.object({
    id: z.uuid().regex(/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/)
});

export const zCompleteUploadResponse = zStoredFile;

export const zGetMeResponse = zMe;

export const zGetMySecurityLogQuery = z.object({
    cursor: z.string().optional(),
    limit: z.int().gte(1).lte(100).optional().default(20)
});

export const zGetMySecurityLogResponse = zSecurityLogPage;

export const zUpdateMyAvatarBody = zUpdateAvatarRequest;

export const zGetLivenessResponse = zLiveness;

export const zGetReadinessResponse = zReadiness;
