export const COMMON_ERROR = {
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  INSUFFICIENT_ROLE: 'INSUFFICIENT_ROLE',
  NOT_FOUND: 'NOT_FOUND',
  UNIQUE_CONSTRAINT: 'UNIQUE_CONSTRAINT',
  FOREIGN_KEY_CONSTRAINT: 'FOREIGN_KEY_CONSTRAINT',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS',
  PAYLOAD_TOO_LARGE: 'PAYLOAD_TOO_LARGE',

  API_UNREACHABLE: 'API_UNREACHABLE',
  API_TIMEOUT: 'API_TIMEOUT',
  API_INVALID_RESPONSE: 'API_INVALID_RESPONSE',
} as const;
