export const FILE_ERROR = {
  FILE_PURPOSE_UNKNOWN: 'FILE_PURPOSE_UNKNOWN',
  FILE_TYPE_NOT_ALLOWED: 'FILE_TYPE_NOT_ALLOWED',
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  FILE_NOT_UPLOADED: 'FILE_NOT_UPLOADED',
  FILE_INVALID_CONTENT: 'FILE_INVALID_CONTENT',
  FILE_NOT_READY: 'FILE_NOT_READY',
  FILE_NOT_FOUND: 'FILE_NOT_FOUND',
  STORAGE_UNAVAILABLE: 'STORAGE_UNAVAILABLE',
  FILE_PROCESSING_BUSY: 'FILE_PROCESSING_BUSY',
} as const;
