import { MS_PER_MINUTE } from '@/lib/constants/time.constants';

export const ACCESS_TOKEN_REFRESH_MARGIN_MS = MS_PER_MINUTE;

export const AUTH_ERROR = {
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  ACCOUNT_TEMPORARILY_LOCKED: 'ACCOUNT_TEMPORARILY_LOCKED',
  EMAIL_TAKEN: 'EMAIL_TAKEN',
  INVALID_CURRENT_PASSWORD: 'INVALID_CURRENT_PASSWORD',
  SESSION_NOT_FOUND: 'SESSION_NOT_FOUND',
} as const;
